server:
  port: 8080

spring:
  application:
    name: om-viewer

app:
  cache-dir: ./cache
  zlbb-base-url: https://zlbb.faendir.com
  puzzle-dir: C:/Users/kuchu/Downloads/OMRecViewer_KvnchRebuild-master/omsim-puzzles/test/puzzle

logging:
  level:
    com.kvnch.omviewer: DEBUG
